.TRY List resources
Currently no resources are managed by LRM.
.TRY Add resource r1 class=ocf type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY Show info r1

Resource ID:r1
Resource agency class:ocf
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY List resources

Resource ID:r1
Resource agency class:ocf
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY Delete resource r1
Succeeded in deleting this resource.
.SETENV dflt_class=lsb
.TRY List resources
Currently no resources are managed by LRM.
.TRY Add resource r1 class=lsb type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY List resources

Resource ID:r1
Resource agency class:lsb
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY Delete resource r1
Succeeded in deleting this resource.
.SETENV dflt_class=heartbeat
.TRY List resources
Currently no resources are managed by LRM.
.TRY Add resource r1 class=heartbeat type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY List resources

Resource ID:r1
Resource agency class:heartbeat
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY Delete resource r1
Succeeded in deleting this resource.
.TRY List resources
Currently no resources are managed by LRM.
.SETENV dflt_class=ocf
.TRY Add resource r1 class=ocf type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY Add resource r1 class=heartbeat type=Dummy provider=heartbeat args=
ERROR: lrm_add_rsc(): got a return code HA_FAIL from a reply message of addrsc with function get_ret_from_msg.
Failed to add this resource.
.TRY Add resource r1 class=ocf type=Dummy provider=heartbeat args=
ERROR: lrm_add_rsc(): got a return code HA_FAIL from a reply message of addrsc with function get_ret_from_msg.
Failed to add this resource.
.TRY Delete resource r1
Succeeded in deleting this resource.
.TRY Add resource r1 class=lsb type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY List resources

Resource ID:r1
Resource agency class:lsb
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY Add resource r2 class=ocf type=Dummy provider=heartbeat args=
Succeeded in adding this resource.
.TRY List resources

Resource ID:r1
Resource agency class:lsb
Resource agency type:Dummy
Resource agency provider:heartbeat

Resource ID:r2
Resource agency class:ocf
Resource agency type:Dummy
Resource agency provider:heartbeat
.TRY Delete resource r1
Succeeded in deleting this resource.
.TRY Delete resource r2
Succeeded in deleting this resource.
.TRY List resources
Currently no resources are managed by LRM.
.TRY Delete resource r1
ERROR: lrm_delete_rsc(): got a return code HA_FAIL from a reply message of delrsc with function get_ret_from_msg.
Failed to delete this resource.
