Currently no resource is managed by LRM.
Succeeded in adding this resource.
Succeeded in adding this resource.
Succeeded in adding this resource.

Resource ID:ip-hb
Resource agency class:heartbeat
Resource agency type:IPaddr
Resource agency provider:default
Resource agency parameters:192.168.58.4  

Resource ID:ip-ocf
Resource agency class:ocf
Resource agency type:IPaddr
Resource agency provider:heartbeat
Resource agency parameters:ipaddr=192.168.58.4  

Resource ID:ip-lsb
Resource agency class:lsb
Resource agency type:Dummy-lsb
Resource agency provider:default
Succeeded in delete this resource.
Succeeded in delete this resource.
Succeeded in delete this resource.
Currently no resource is managed by LRM.
