#!/bin/bash
../admin/lrmadmin -L
../admin/lrmadmin -A ip-hb heartbeat IPaddr NULL 192.168.58.4
../admin/lrmadmin -A ip-ocf ocf IPaddr heartbeat ipaddr=192.168.58.4
../admin/lrmadmin -A ip-lsb lsb Dummy-lsb NULL 
../admin/lrmadmin -L
../admin/lrmadmin -D ip-hb
../admin/lrmadmin -D ip-ocf
../admin/lrmadmin -D ip-lsb
../admin/lrmadmin -L

