#!/bin/sh
#
# Copyright (c) 2004 SUSE LINUX AG, Lars Marowsky-Brée
#                    All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
#

PIDFILE=/tmp/Dummy-lsb.pid

case $1 in
start)		echo $0>$PIDFILE
		exit 0
		;;
		
stop)		if [ -e $PIDFILE ]; then
			rm $PIDFILE -f
		fi
		exit 0
		;;
		
restart)	echo $0>$PIDFILE
		exit 0
		;;
		
reload)		echo $0>$PIDFILE
		exit 0
		;;
		
force-reload)	echo $0>$PIDFILE
		exit 0
		;;
		
status)		if [ -e $PIDFILE ]; then
			exit 0
		else
			exit 3
		fi
		;;	
	
*)		echo 'usage: $0 {start|stop|restart|reload|force-reload|status}'
		exit 0
		;;
esac

