lrmd daemon is running.
Support 4 RA classes
lsb
ocf
heartbeat
stonith
List size: 0
For this RA class, no any RA type is supported
List size: 0
For this RA class, no any RA type is supported
List size: 21
RA type name: portblock
RA type name: db2
RA type name: apache
RA type name: Xinetd
RA type name: WinPopup
RA type name: WAS
RA type name: ServeRAID
RA type name: SendArp
RA type name: Raid1
RA type name: OCF
RA type name: MailTo
RA type name: LinuxSCSI
RA type name: LVM
RA type name: IPv6addr
RA type name: IPsrcaddr
RA type name: IPaddr2
RA type name: IPaddr
RA type name: ICP
RA type name: Filesystem
RA type name: Delay
RA type name: AudibleAlarm
metadata of sshd(lsb) is: sshd
metadata of IPv6addr(heartbeat) is: IPv6addr
heartbeat
failsafe
