../admin/lrmadmin -A ip-hb heartbeat IPaddr NULL 192.168.58.4
Succeeded in adding this resource.
../admin/lrmadmin -E ip-hb status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:3
output data:
stopped

---------------------------------------

../admin/lrmadmin -E ip-hb start  0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:start
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E ip-hb status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:0
output data:
running

---------------------------------------

../admin/lrmadmin -E ip-hb stop   0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:stop
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E ip-hb status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:3
output data:
stopped

---------------------------------------

../admin/lrmadmin -D ip-hb
Succeeded in delete this resource.
../admin/lrmadmin -A ip-ocf ocf IPaddr heartbeat ipaddr=192.168.58.4
Succeeded in adding this resource.
../admin/lrmadmin -E ip-ocf meta-data 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:meta-data
operation status:succeed
return code:0
output data:

<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="IPaddr" version="0.1">
  <version>1.0</version>
  <parameters>
    <parameter name="ipaddr" unique="0">
      <longdesc lang="en">
        This script manages IP alias IP addresses,It can add an IP alias, or 
        remove one. 
      </longdesc>
      <shortdesc lang="en">manages IP alias</shortdesc>
      <content type="string" default="" />
    </parameter>
  </parameters>
  <actions>
    <action name="start"   timeout="15" />
    <action name="stop"    timeout="15" />
    <action name="status"  timeout="15" interval="15" start-delay="15" />
    <action name="monitor" timeout="15" interval="15" start-delay="15" />
    <action name="meta-data"  timeout="5" />
  </actions>
  <special tag="heartbeat">
    <version>2.0</version>
  </special>
</resource-agent>


---------------------------------------

../admin/lrmadmin -E ip-ocf monitor 0 0 EVERYTIME OCF_CHECK_LEVEL=0
waiting for calling result from the lrmd.
----------------operation--------------
type:monitor
operation status:succeed
return code:1
output data:
down

---------------------------------------

../admin/lrmadmin -E ip-ocf start  0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:start
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E ip-ocf monitor 0 0 EVERYTIME OCF_CHECK_LEVEL=0
waiting for calling result from the lrmd.
----------------operation--------------
type:monitor
operation status:succeed
return code:0
output data:
OK

---------------------------------------

../admin/lrmadmin -E ip-ocf stop   0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:stop
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E ip-ocf monitor 0 0 EVERYTIME OCF_CHECK_LEVEL=0
waiting for calling result from the lrmd.
----------------operation--------------
type:monitor
operation status:succeed
return code:1
output data:
down

---------------------------------------

../admin/lrmadmin -D ip-ocf
Succeeded in delete this resource.
../admin/lrmadmin -A dummy lsb Dummy-lsb NULL
Succeeded in adding this resource.
../admin/lrmadmin -E dummy status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:13
output data:
(null)
---------------------------------------

../admin/lrmadmin -E dummy start  0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:start
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E dummy status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E dummy stop   0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:stop
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E dummy status 0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:13
output data:
(null)
---------------------------------------

../admin/lrmadmin -D dummy
Succeeded in delete this resource.
