#!/bin/bash
echo "../admin/lrmadmin -A ip heartbeat IPaddr 192.168.58.4"
../admin/lrmadmin -A ip heartbeat IPaddr 192.168.58.4

echo "../admin/lrmadmin -E ip status 0 1000 CHANGED &"
../admin/lrmadmin -E ip status 0 1000 CHANGED &

sleep 5

echo "../admin/lrmadmin -E ip start  0 0 EVERYTIME"
../admin/lrmadmin -E ip start  0 0 EVERYTIME


echo "../admin/lrmadmin -E ip status 0 1000 CHANGED &"
../admin/lrmadmin -E ip status 0 1000 CHANGED &

sleep 5

echo "../admin/lrmadmin -E ip stop   0 0 EVERYTIME"
../admin/lrmadmin -E ip stop   0 0 EVERYTIME

sleep 5

echo "../admin/lrmadmin -D ip"
../admin/lrmadmin -D ip

