../admin/lrmadmin -A ip heartbeat IPaddr 192.168.58.4
Succeeded in adding this resource.
../admin/lrmadmin -E ip status 0 0 3
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:3
output data:
stopped

---------------------------------------

../admin/lrmadmin -E ip status 0 1000 0 &
../admin/lrmadmin -E ip start  0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:0
output data:
running

---------------------------------------

waiting for calling result from the lrmd.
----------------operation--------------
type:start
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

../admin/lrmadmin -E ip status 0 0 0
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:0
output data:
running

---------------------------------------

../admin/lrmadmin -E ip status 0 1000 3 &
../admin/lrmadmin -E ip stop   0 0 EVERYTIME
waiting for calling result from the lrmd.
----------------operation--------------
type:stop
operation status:succeed
return code:0
output data:
(null)
---------------------------------------

waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:3
output data:
stopped

---------------------------------------

../admin/lrmadmin -E ip status 0 0 3
waiting for calling result from the lrmd.
----------------operation--------------
type:status
operation status:succeed
return code:3
output data:
stopped

---------------------------------------

../admin/lrmadmin -D ip
Succeeded in delete this resource.
