#!/bin/bash
echo "../admin/lrmadmin -A ip heartbeat IPaddr NULL 192.168.58.4"
../admin/lrmadmin -A ip heartbeat IPaddr NULL 192.168.58.4

echo "../admin/lrmadmin -E ip status 0 0 3"
../admin/lrmadmin -E ip status 0 0 3

sleep 2

echo "../admin/lrmadmin -E ip status 0 1000 0 &"
../admin/lrmadmin -E ip status 0 1000 0 &

sleep 2

echo "../admin/lrmadmin -E ip start  0 0 EVERYTIME"
../admin/lrmadmin -E ip start  0 0 EVERYTIME

sleep 2

echo "../admin/lrmadmin -E ip status 0 0 0"
../admin/lrmadmin -E ip status 0 0 0

sleep 2

echo "../admin/lrmadmin -E ip status 0 1000 3 &"
../admin/lrmadmin -E ip status 0 1000 3 &

sleep 2

echo "../admin/lrmadmin -E ip stop   0 0 EVERYTIME"
../admin/lrmadmin -E ip stop   0 0 EVERYTIME

sleep 2

echo "../admin/lrmadmin -E ip status 0 0 3"
../admin/lrmadmin -E ip status 0 0 3

sleep 2

echo "../admin/lrmadmin -D ip"
../admin/lrmadmin -D ip

