.TH MEATCLIENT 8 "27th March 2003"
.SH NAME
stonith \- extensible interface for remotely powering down a node in the cluster
.SH SYNOPSIS
.br
\fBmeatclinet\fP [ -c nodename ]
.SH DESCRIPTION
meatclient is a program that confirms that a manual reset has been done
when stonith needed an operator to power-cycle a node on it's behalf.
.SH OPTIONS
.TP
.B \-c nodename:
manual power reset has been done on the node.
.SH "SEE ALSO"
.PP
heartbeat (8)
stonith (8)
.SH AUTHORS
.nf
meatclient - Gregor Binder <gbinder@sysfive.com>
man page - Michael Moerz <mikem@debian.org>, Horms <horms@vergenet.net>
.fi
