.TH  HA_LOGD 8 "5th November 2004"
.SH NAME
ha_logd \- Logging Daemon for High-Availability Linux
.SH SYNOPSIS
.B ha_logd
.nh
.RI "[ -skdh ] [ -c configure file ]"
.SH DESCRIPTION
\fBha_logd\fP is a logging daemon for 
Linux-HA. It receives messages from a local domain socket \fB/var/lib/log_daemon\fP,
writes them to appropriate files and syslog if enabled. The reason the logging
daemon is written is that occationally Heartbeat suffers from disk I/O delays. By
sending log messages to logging daemon, heatbeat can avoid disk I/O delays. 
.PP
.SH OPTIONS
.IP -s  
Show the status of ha_logd, running or stopped. 
.IP -k
Stop (kill) the daemon
.IP -d
Make the logging daemon a daemon
.IP -h
Show help message
.IP "-c configure file"
Configure file for ha_logd.
User can configure log file, debuf file, log facility, entity and useapphbd.
 For details, see sample configure file ha_logd.cf.
.PP
.SH FILES
.I /var/run/ha_logd.pid  
Default PID file.
.PP
.I ha_logd.cf  
Sample config file for ha_logd. 
This file is installed together with other Heartbeat documents.

.SH SEE ALSO
heartbeat(8) ha_logger(8)

.SH DOCUMENTATION
More information may be found at http://www.linux-ha.org.

.SH AUTHORS
.nf
 Guochun Shi <gshi@ncsa.uiuc.edu>
 Alan Robertson <alanr@unix.sh>
 Lars Marowsky-Bree <lmb@suse.de> 
.fi

